import React, {type ReactNode, useState} from 'react';
import {type Language, LanguageContext} from "./UseLanguage";

const translations = {
  es: {
    'nav.resume': 'CURRÍCULUM',
    'nav.gallery': 'DIBUJOS',
    'resume.title': 'Desarrollador web full stack freelance',
    'resume.location': 'Valencia',
    'resume.hero_desc': 'Atención al detalle y entrega de calidad. Siempre en proceso de aprendizaje.',
    'resume.experience': 'Experiencia',
    'resume.exp1_title': 'Desarrollador full stack',
    'resume.exp1_company': 'Autónomo - Valencia',
    'resume.exp1_desc': 'Proyectos en modalidad freelance.',
    'resume.exp2_title': 'Desarrollador full stack',
    'resume.exp2_company': 'LetsReg - Oslo',
    'resume.exp2_desc': 'Desarrollo de la aplicación web de gestión de eventos y servicios auxiliares.',
    'resume.exp3_title': 'Desarrollador full stack',
    'resume.exp3_company': 'Danske Bank - Copenhague',
    'resume.exp3_desc': 'Diseño y desarrollo de una aplicación web y servicios auxiliares para la gestión de préstamos a proyectos y productos sostenibles.',
    'resume.exp4_title': 'Desarrollador',
    'resume.exp4_company': 'IIC (tiempo parcial) - Madrid',
    'resume.exp4_desc': 'Conversión de scripts extensos en microservicios y estudio de viavilidad de tecnologías para aplicarlas en la empresa.',
    'resume.exp5_title': 'Desarrollador',
    'resume.exp5_company': 'Flexxible (prácticas) - Madrid',
    'resume.exp5_desc': 'Automatización de la configuración y despliegue de máquinas virtuales.',
    'resume.education': 'Educación',
    'resume.edu1_title': 'Grado en Ingeniería Informática',
    'resume.edu1_company': 'UAM - Madrid',
    'resume.skills': 'Habilidades',
    'resume.languages': 'Lenguas',
    'resume.lang_es': 'Español',
    'resume.lang_es_level': 'Nativo',
    'resume.lang_en': 'Inglés',
    'resume.lang_en_level': 'Avanzado',
    'resume.lang_da': 'Danés',
    'resume.lang_da_level': 'Avanzado',
    'resume.projects': 'Proyectos Destacados',
    'resume.proj1_title': 'AI prompt (2025)',
    'resume.proj2_title': 'Fabricante de muebles (2025)',
    'resume.proj3_title': 'Portafolio de fotografía (2025)',
    'resume.proj4_title': 'Urban Sketchers (2025)',
    'resume.this_web': 'Esta web (2025)',
    'resume.proj6_title': 'Alex Lomart (2019)',
    'resume.this_web_desc': 'Sitio web en el que me expongo al público.',
    'resume.ai_prompt_desc': 'Plataforma que permite al usuario chatear con una interfaz que tiene acceso a parte del ecosistema Microsoft del usuario.',
    'resume.furniture_desc': 'Sitio web que podría ser utilizado por un fabricante de muebles.',
    'resume.photography_desc': 'Sitio web que podría ser usado por un fotógrafo.',
    'resume.urban_desc': 'Sitio web que podría ser usado por un grupo de Urban Sketchers.',
    'resume.alex_desc': 'Portafolio de un fotógrafo profesional.',
    'resume.present': 'Presente',
    'gallery.title': 'Galería de dibujos',
    'gallery.loading': 'Cargando galería...',
    'footer.copy': '© {year} David Paarup',
  },
  en: {
    'nav.resume': 'RESUME',
    'nav.gallery': 'DRAWINGS',
    'resume.title': 'Freelance full stack web developer',
    'resume.location': 'Valencia',
    'resume.hero_desc': 'Attention to detail and quality delivery. Always in a learning process.',
    'resume.experience': 'Experience',
    'resume.exp1_title': 'Full stack developer',
    'resume.exp1_company': 'Freelance - Valencia',
    'resume.exp1_desc': 'Freelance projects.',
    'resume.exp2_title': 'Full stack developer',
    'resume.exp2_company': 'LetsReg - Oslo',
    'resume.exp2_desc': 'Development of web application for event management and auxiliary services.',
    'resume.exp3_title': 'Full stack developer',
    'resume.exp3_company': 'Danske Bank - Copenhagen',
    'resume.exp3_desc': 'Design and development of a web application and auxiliary services for managing loans to sustainable projects and products.',
    'resume.exp4_title': 'Developer',
    'resume.exp4_company': 'IIC (part-time) - Madrid',
    'resume.exp4_desc': 'Conversion of extensive scripts into microservices and feasibility study of technologies for implementation in the company.',
    'resume.exp5_title': 'Developer',
    'resume.exp5_company': 'Flexxible (internship) - Madrid',
    'resume.exp5_desc': 'Automation of configuration and deployment of virtual machines.',
    'resume.education': 'Education',
    'resume.edu1_title': 'BSc in Computer Engineering',
    'resume.edu1_company': 'UAM - Madrid',
    'resume.skills': 'Skills',
    'resume.languages': 'Languages',
    'resume.lang_es': 'Spanish',
    'resume.lang_es_level': 'Native',
    'resume.lang_en': 'English',
    'resume.lang_en_level': 'Advanced',
    'resume.lang_da': 'Danish',
    'resume.lang_da_level': 'Advanced',
    'resume.projects': 'Featured Projects',
    'resume.proj1_title': 'AI prompt (2025)',
    'resume.proj2_title': 'Furniture maker (2025)',
    'resume.proj3_title': 'Photography portfolio (2025)',
    'resume.proj4_title': 'Urban Sketchers (2025)',
    'resume.this_web': 'This website (2025)',
    'resume.proj6_title': 'Alex Lomart (2019)',
    'resume.this_web_desc': 'Website where I expose myself to the public.',
    'resume.ai_prompt_desc': 'Platform that allows users to chat with an interface that has access to part of the user\'s Microsoft ecosystem.',
    'resume.furniture_desc': 'Website that could be used by a furniture manufacturer.',
    'resume.photography_desc': 'Website that could be used by a photographer.',
    'resume.urban_desc': 'Website that could be used by an Urban Sketchers group.',
    'resume.alex_desc': 'Portfolio of a professional photographer.',
    'resume.present': 'Present',
    'gallery.title': 'Drawings gallery',
    'gallery.loading': 'Loading gallery...',
    'footer.copy': '© {year} David Paarup',
  },
  da: {
    'nav.resume': 'CV',
    'nav.gallery': 'TEGNINGER',
    'resume.title': 'Freelance full stack webudvikler',
    'resume.location': 'Valencia',
    'resume.hero_desc': 'Opmærksomhed på detaljer og levering af høj kvalitet. Altid i en læreproces.',
    'resume.experience': 'Erfaring',
    'resume.exp1_title': 'Full stack udvikler',
    'resume.exp1_company': 'Freelance - Valencia',
    'resume.exp1_desc': 'Freelance projekter.',
    'resume.exp2_title': 'Full stack udvikler',
    'resume.exp2_company': 'LetsReg - Oslo',
    'resume.exp2_desc': 'Udvikling af webapplikation til eventstyring og hjælpetjenester.',
    'resume.exp3_title': 'Full stack udvikler',
    'resume.exp3_company': 'Danske Bank - København',
    'resume.exp3_desc': 'Design og udvikling af en webapplikation og hjælpetjenester til administration af lån til bæredygtige projekter og produkter.',
    'resume.exp4_title': 'Udvikler',
    'resume.exp4_company': 'IIC (deltid) - Madrid',
    'resume.exp4_desc': 'Konvertering af omfattende scripts til mikrotjenester og gennemførlighedsstudie af teknologier til implementering i virksomheden.',
    'resume.exp5_title': 'Udvikler',
    'resume.exp5_company': 'Flexxible (praktik) - Madrid',
    'resume.exp5_desc': 'Automatisering af konfiguration og udrulning af virtuelle maskiner.',
    'resume.education': 'Uddannelse',
    'resume.edu1_title': 'BSc i datalogi',
    'resume.edu1_company': 'UAM - Madrid',
    'resume.skills': 'Færdigheder',
    'resume.languages': 'Sprog',
    'resume.lang_es': 'Spansk',
    'resume.lang_es_level': 'Modersmål',
    'resume.lang_en': 'Engelsk',
    'resume.lang_en_level': 'Avanceret',
    'resume.lang_da': 'Dansk',
    'resume.lang_da_level': 'Avanceret',
    'resume.projects': 'Udvalgte Projekter',
    'resume.proj1_title': 'AI prompt (2025)',
    'resume.proj2_title': 'Møbelproducent (2025)',
    'resume.proj3_title': 'Fotoportfolio (2025)',
    'resume.proj4_title': 'Urban Sketchers (2025)',
    'resume.this_web': 'Denne webside (2025)',
    'resume.proj6_title': 'Alex Lomart (2019)',
    'resume.this_web_desc': 'Hjemmeside, hvor jeg præsenterer mig selv for offentligheden.',
    'resume.ai_prompt_desc': 'Platform, der lader brugere chatte med en grænseflade, der har adgang til dele af brugerens Microsoft-økosystem.',
    'resume.furniture_desc': 'Hjemmeside, der kunne bruges af en møbelproducent.',
    'resume.photography_desc': 'Hjemmeside, der kunne bruges af en fotograf.',
    'resume.urban_desc': 'Hjemmeside, der kunne bruges af en Urban Sketchers-gruppe.',
    'resume.alex_desc': 'Portfolio for en professionel fotograf.',
    'resume.present': 'Nuværende',
    'gallery.title': 'Galleri med tegninger',
    'gallery.loading': 'Indlæser galleri...',
    'footer.copy': '© {year} David Paarup',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const browserLang = navigator.language.split('-')[0];
    if (browserLang === 'es') {
      return 'es';
    }
    if (browserLang === 'da') {
      return 'da';
    }
    return 'en';
  });

  const t = (key: string): string => {
    return (translations[language] as never)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

